name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code
         uses: actions/checkout@v2
       - name: Install Node.js, NPM and Yarn
         uses: actions/setup-node@v1
         with:
            node-version: 16
       - name: Install Dependencies
         run: |
              npm ci
       - uses: mikeal/merge-release@master
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}